DELIMITER ||
CREATE TRIGGER correct_hash BEFORE INSERT ON hash_info
	FOR EACH ROW
		BEGIN
			IF NEW.hash NOT REGEXP '(Q)[a-zA-Z0-9_]{45}' THEN
				SIGNAL SQLSTATE '99999'
					SET MESSAGE_TEXT = 'Wrong hash';
			END IF;
		END;
||